/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Analysis: typeof import('./components/views/Analysis.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    Browse: typeof import('./components/views/Browse.vue')['default']
    Contact: typeof import('./components/views/Contact.vue')['default']
    Download: typeof import('./components/views/Download.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Help: typeof import('./components/views/Help.vue')['default']
    Home: typeof import('./components/views/Home.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Statistics: typeof import('./components/views/Statistics.vue')['default']
  }
}
